source_id: 1lc6VxNxAvdm4KOsDthpTtQqbfVWaFTeZFjFyIMVg_0M
sheets:
  - name: Template
    regions:
      - name: Students_Info
        start: A1
        end: H7
        contains_headers: true
        types:
          Class: string
          Professor: string
          Professor Email: string
          Attendance: string
          Student Name: string
          Student Email: string
          Advisor: string
          Advisor Email: string
      - name: Students_Grades
        start: I1
        end: U7
        contains_headers: true
        types:
          Total: string
          Assignment 1: string
          Assignment 2: string
          Assignment 3: string
          Assignment 4: string
          Assignment 5: string
          Assignment 6: string
          Assignment 7: string
          Assignment 8: string
          Assignment 9: string
          Assignment 10: string
          Assignment 11: string
          Assignment 12: string
  - name: Example
    regions:
      - name: Students_Info
        start: A1
        end: H7
        contains_headers: true
        types:
          Class: string
          Professor: string
          Professor Email: string
          Attendance: string
          Student Name: string
          Student Email: string
          Advisor: string
          Advisor Email: string
      - name: Students_Grades
        start: I1
        end: U7
        contains_headers: true
        types:
          Total: string
          Assignment 1: string
          Assignment 2: string
          Assignment 3: string
          Assignment 4: string
          Assignment 5: string
          Assignment 6: string
          Assignment 7: string
          Assignment 8: string
          Assignment 9: string
          Assignment 10: string
          Assignment 11: string
          Assignment 12: string